"""
inspect_case.py — Side-by-side view of one ConGra case across all pilot runs.

Shows the conflict region (sides a vs b), the ground-truth resolution, and
every model resolution recorded in any scripts/results/pilot_results_*.jsonl
file for that case.

Usage:
    python3 scripts/inspect_case.py <case_id_substring>

Example:
    python3 scripts/inspect_case.py 0xe4ff79aa

LaTeX mode writes a paste-ready worked example instead of the text dump:

    python3 scripts/inspect_case.py 0x96d20e6c --latex --pilot-only \
        --show apertus:no-skill,apertus:skill-v2-sys \
        --out results_overleaf_figures/skill-design-loop

WARNING: scripts/results/ holds TWO run families and they disagree per case.
The n=20 pilot (pilot_results_<model>.jsonl, _skill-v2, _skill-v2.1) is what the
skill-design sections report; the full slice (..._python_tiny.jsonl, ~3,597 cases)
is what the RQ1 figures use. Pass --pilot-only for anything that goes into those
sections, or the numbers will silently come from the wrong scale.

The argument matches any case_id that contains the substring, so an 8-hex-char
prefix (as used in analysis docs) is enough.
"""

import argparse
import glob
import json
import os
import sys


REPO_ROOT   = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
RESULTS_DIR = os.path.join(REPO_ROOT, "scripts", "results")
CONGRA_ROOT = os.path.abspath(os.path.join(REPO_ROOT, "..", "ConGra"))
DATA_ROOT   = os.path.join(CONGRA_ROOT, "data", "congra_tiny_datasets", "python", "func")
META_PATH   = os.path.join(DATA_ROOT, "meta_list.txt")


def load_conflict_region(case_id: str) -> tuple[str, str, str] | None:
    """Returns (conflict_context, conflict_text, ground_truth) for the given
    case_id by looking it up in meta_list.txt and reading the dataset files.
    Returns None if the case is not found in meta_list.txt."""
    with open(META_PATH) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            parts = line.split(": ")
            if len(parts) != 3:
                continue
            source_path, hash_idx, conflict_idx = parts
            if case_id in hash_idx:
                conflict_idx = int(conflict_idx)
                source_full  = os.path.join(CONGRA_ROOT, "data", "raw_datasets", source_path)
                hash_file    = os.path.join(DATA_ROOT, hash_idx)
                return _load_conflict_and_answer(source_full, hash_file, conflict_idx, n=5)
    return None


def _load_conflict_and_answer(source_path: str, file_path: str, k: int, n: int):
    """Lifted from pilot.py. Returns (conflict_context, conflict_text, ground_truth)."""
    region_path = source_path.replace("merged_without_base", "regions") + ".region"
    regions = []
    with open(region_path) as f:
        for line in f:
            if "#" in line:
                continue
            line = line.strip()
            if line:
                regions.append(eval(line))
    region = regions[k - 1]

    with open(file_path, encoding="utf-8", errors="ignore") as f:
        lines = f.read().split("\n")
    start, end = region[0] - 1, region[1]
    conflict_text    = "\n".join(lines[start:end])
    conflict_context = "\n".join(lines[max(0, start - n):end + n])

    resolved_path = source_path.replace("merged_without_base", "resolved").replace("regions", "resolved")
    with open(resolved_path, encoding="utf-8", errors="ignore") as f:
        rlines = f.read().split("\n")
    rstart, rend = region[2] - 1, region[3]
    ground_truth = "\n".join(rlines[max(0, rstart):rend])

    return conflict_context, conflict_text, ground_truth


# The n=20 pilot family is every pilot_results_* file that is NOT a full-slice run
# and not the 32B pair. See the module docstring: the two families disagree per case.
FULL_SLICE_MARKERS = ("python_tiny", "32b")

MODEL_ALIASES = {
    "apertus": "Apertus-8B-Instruct-2509",
    "qwen3":   "Qwen3-8B",
}
DISPLAY_NAMES = {
    "Apertus-8B-Instruct-2509": "Apertus-8B",
    "Qwen3-8B":                 "Qwen3-8B",
}

LISTING_STYLE = r"""% Listing style for the worked conflict examples.
% Generated by scripts/inspect_case.py --latex. \input this once in the preamble.
%
% Uses title=, never caption=: the thesis preamble renames \lstlistingname to
% "Algorithmus", which would show up on any captioned listing in an English
% thesis. title= prints the heading without that prefix and keeps these listings
% out of the list of listings, where they do not belong.
%
% Needs only listings + xcolor, both already loaded.
\lstdefinestyle{conflictcode}{
  basicstyle=\ttfamily\footnotesize,
  breaklines=true, columns=fullflexible, keepspaces=true,
  showstringspaces=false, frame=single, framesep=4pt,
  rulecolor=\color{black!30}, xleftmargin=12pt,
  aboveskip=1.2em, belowskip=0.6em,
  postbreak=\mbox{\textcolor{gray}{$\hookrightarrow$}\space},
  literate={—}{{-{}-{}-}}3 {–}{{-{}-}}2 {→}{{$\rightarrow$}}1 {…}{{\ldots}}1
}
"""


def is_pilot_file(filename: str) -> bool:
    return not any(marker in filename for marker in FULL_SLICE_MARKERS)


def find_matching_records(case_substring: str, pilot_only: bool = False) -> list[tuple[str, dict]]:
    """Returns [(filename, record), ...] for every record whose case_id contains the substring."""
    matches = []
    for path in sorted(glob.glob(os.path.join(RESULTS_DIR, "pilot_results_*.jsonl"))):
        filename = os.path.basename(path)
        if pilot_only and not is_pilot_file(filename):
            continue
        with open(path) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    r = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if case_substring in r.get("case_id", ""):
                    matches.append((filename, r))
    return matches


def _pick(records, model_key, condition):
    """The one record for this model+condition, or None."""
    want = MODEL_ALIASES.get(model_key, model_key)
    for _, r in records:
        if r.get("model", "").split("/")[-1] == want and r.get("condition") == condition:
            return r
    return None


def _block(title, body):
    return (f"\\begin{{lstlisting}}[style=conflictcode,title={{{title}}}]\n"
            f"{body.rstrip()}\n"
            f"\\end{{lstlisting}}\n\n")


def _condition_label(condition):
    if condition == "no-skill":
        return "without the skill"
    name = condition.replace("skill-", "")
    for suffix, where in (("-sys", "system prompt"), ("-user", "user prompt")):
        if name.endswith(suffix):
            return f"with {name[:-len(suffix)]} in the {where}"
    return f"with {name}"


def emit_latex(case_substring, region, records, show, out_dir):
    """Writes a paste-ready worked example: the conflict, the ground truth, and
    one listing per requested model+condition."""
    _, conflict_text, ground_truth = region
    case_id = records[0][1].get("case_id", case_substring)

    out = [
        f"% Worked example: conflict {case_id} (ConGra python/func, n=20 pilot).\n",
        "% Generated by scripts/inspect_case.py --latex --pilot-only.\n",
        "% Regenerate rather than edit by hand: a hand-edited copy drifts from the repo.\n",
        "% Requires \\input{case_listing_style} in the preamble.\n",
        "%\n",
        "% Every number below is n=20 pilot, NOT the full slice.\n\n",
    ]
    out.append(_block(f"\\textbf{{The conflict}} (\\texttt{{{case_id}}})", conflict_text))
    gt_lines = len(ground_truth.strip().split("\n"))
    out.append(_block(f"\\textbf{{Ground-truth resolution}} ({gt_lines} lines, "
                      f"{len(ground_truth)} characters)", ground_truth))

    for spec in show:
        model_key, condition = spec.split(":", 1)
        r = _pick(records, model_key, condition)
        if r is None:
            print(f"  [!] no pilot record for {spec} - skipped")
            continue
        m = r.get("metrics") or {}
        display = DISPLAY_NAMES.get(r["model"].split("/")[-1], r["model"])
        resolution = r.get("resolution") or ""
        title = (f"\\textbf{{{display}, {_condition_label(condition)}}} --- "
                 f"edit {m.get('edit'):.3f}, winnowing {m.get('winnowing'):.3f}, "
                 f"{len(resolution)} characters")
        out.append(_block(title, resolution))

    os.makedirs(out_dir, exist_ok=True)
    style_path = os.path.join(out_dir, "case_listing_style.tex")
    with open(style_path, "w") as f:
        f.write(LISTING_STYLE)
    frag_path = os.path.join(out_dir, f"case_{case_id}.tex")
    with open(frag_path, "w") as f:
        f.write("".join(out))
    print(f"Wrote: {frag_path}")
    print(f"Wrote: {style_path}")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("case_id", help="Case id (or substring; e.g. '0xe4ff79aa')")
    parser.add_argument("--pilot-only", action="store_true",
                        help="restrict to the n=20 pilot family (see the module docstring)")
    parser.add_argument("--latex", action="store_true",
                        help="write a paste-ready .tex worked example instead of the text dump")
    parser.add_argument("--show", default="",
                        help="comma-separated model:condition pairs to include as listings, "
                             "e.g. apertus:no-skill,apertus:skill-v2-sys")
    parser.add_argument("--out", default=".", help="directory for --latex output")
    args = parser.parse_args()

    case_substring = args.case_id

    if args.latex:
        region = load_conflict_region(case_substring)
        if region is None:
            sys.exit(f"[!] Case '{case_substring}' not found in {META_PATH}")
        records = find_matching_records(case_substring, pilot_only=args.pilot_only)
        if not records:
            sys.exit(f"[!] No result records for '{case_substring}'")
        if not args.pilot_only:
            print("[!] WARNING: --latex without --pilot-only mixes pilot and full-slice runs")
        show = [p for p in args.show.split(",") if p.strip()]
        emit_latex(case_substring, region, records, show, args.out)
        return

    print("=" * 78)
    print(f"CASE: {case_substring}")
    print("=" * 78)

    # 1. Conflict region from the dataset.
    region = load_conflict_region(case_substring)
    if region is None:
        print(f"\n[!] Case '{case_substring}' not found in {META_PATH}")
    else:
        conflict_context, conflict_text, ground_truth = region
        print("\n--- CONFLICT REGION (with surrounding context, n=5) ---\n")
        print(conflict_context)
        print("\n--- CONFLICT TEXT (markers and bodies only) ---\n")
        print(conflict_text)
        print("\n--- GROUND TRUTH RESOLUTION ---\n")
        print(ground_truth)

    # 2. All matching records across every pilot run.
    matches = find_matching_records(case_substring, pilot_only=args.pilot_only)
    if not matches:
        print(f"\n[!] No pilot result records found for '{case_substring}' in {RESULTS_DIR}")
        sys.exit(0)

    print(f"\n--- MODEL OUTPUTS ({len(matches)} records across pilot runs) ---")
    for filename, r in matches:
        metrics = r.get("metrics", {})
        edit = metrics.get("edit")
        winnowing = metrics.get("winnowing")
        print()
        print(f"[{filename}] condition={r.get('condition')} model={r.get('model')}")
        print(f"  edit={edit}  winnowing={winnowing}")
        print("  --- resolution ---")
        for line in (r.get("resolution") or "").split("\n"):
            print(f"  {line}")


if __name__ == "__main__":
    main()
